create table if not exists public.friend_edges (
  id bigint generated by default as identity primary key,
  follower_id uuid not null,
  followed_id uuid not null,
  created_at timestamptz not null default now(),
  unique (follower_id, followed_id)
);

create table if not exists public.movie_stamps (
  id bigint generated by default as identity primary key,
  movie_id integer not null,
  user_id uuid not null,
  stamp text not null,
  score integer not null check (score between 1 and 5),
  created_at timestamptz not null default now()
);

create index if not exists idx_movie_stamps_movie_id on public.movie_stamps(movie_id);
create index if not exists idx_movie_stamps_user_id on public.movie_stamps(user_id);
create index if not exists idx_friend_edges_follower on public.friend_edges(follower_id);
